config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :communications
  resources :orders do
    member do 
      patch :complete 
    end
  end

  resources :products do
    member do 
      patch :available 
    end
  end
  

  resources :categories do
    member do 
      patch :available 
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  
  resources :categories
  get 'users/show'
  get 'admin/index'
  get 'admin/help'
  get 'admin/order'
  get 'admin/edit'
  get 'admin/products'
  get 'admin/orderarchive'
  get 'admin/landingpage'

  get '/start', to: 'admin#landingpage'
  get '/deals', to: 'admin#deals'
  get '/sales', to: 'communications#new'
  get '/support', to: 'communications#new'
  get '/help', to: 'admin#help'

  get "menu/:id" => "store#menu", as: :menu

  get '' => 'store#profile', constraints: {subdomain: /.+/}

  resources :store
  resources :line_items
  resources :carts
  get 'store/index'
  resources :products
  
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :projects do
    resources :comments, module: :projects
  end
  

  resource :subscription
  root to: 'admin#landingpage'

end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_product(product)
        current_item = line_items.find_by(product_id: product.id)

        if current_item
          current_item.increment(:quantity)
           else 
          current_item = line_items.build(product_id: product.id)
        end
        current_item
    end 
      
    def total_price
      line_items.to_a.sum{ |item| item.total_price }
    end 
      
end

app/models/category.rb
class Category < ApplicationRecord
    validates :category, presence: true 
    validates :Type, presence: true 

    has_many :products
    belongs_to :user

    enum Type: {
        "Food Menu" => "food",
        "Drinks Menu" => "drink"
    }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/communication.rb
class Communication < ApplicationRecord
    validates :name, :text, :email, :company, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product
  belongs_to :cart, optional: true

  def total_price 
    product.price * quantity
  end 
  
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, dependent: :destroy
    validates :name, presence: true

    enum type: {
      "Table Service" => "1",
      "Collection" => "2"
  }

  
    def add_line_items_from_cart(cart)
      cart.line_items.each do |item|
        item.cart_id = nil
        line_items << item
      end
    end
  
end

app/models/perk.rb
class Perk < ApplicationRecord
  belongs_to :project
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title , :category_id, presence: true 
    validates :price, numericality: { greater_than_or_equal_to: 0.01 }
    belongs_to :user
    belongs_to :category
    has_many :line_items 
    before_destroy :ensure_not_referenced_by_any_line_item
    private 

    def ensure_not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, 'Line Items present')
            throw :abort
        end
    end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_rich_text :description
  has_one_attached :thumbnail
  has_many :comments, as: :commentable
  has_many :perks, dependent: :destroy
  accepts_nested_attributes_for :perks, allow_destroy: true, reject_if: proc { |attr| attr['title'].blank? }

  scope :active, ->{ where(status: "active") }
  scope :inactive, ->{ where(status: "inactive") }

  def backers
    # find users who backed a specific project
  end

  def active?
    status == "active"
  end

  def inactive
    status == "inactive"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:stripe_connect]

  has_many :projects, dependent: :destroy
  has_many :categories

  validates :email, uniqueness:true 
  validates :s_name, presence:true
  validates :username, uniqueness:true 


  def can_receive_payments?
    uid? &&  provider? && access_code? && publishable_key?
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def purchased_perk(perk)
    user_signed_in? && current_user.perk_subscriptions.include?("#{perk.title.parameterize}-perk_#{perk.id}")
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tailwind Admin Template</title>
  <link rel="stylesheet" href="public/css/tailwind.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"
    integrity="sha256-XF29CBwU1MWLaGEnsELogU6Y6rcc5nCkhhx89nFMIDQ=" crossorigin="anonymous"></script>
  <style>
    .divider {
      border-top: 1px solid rgba(255, 255, 255, .15);
    }

    .rotate-15 {
      transform: rotate(-15deg);
    }

    .notification {
      top: 1px;
      right: 1px;
      font-size: 10px;
      padding: 2px 4px;
    }

  /* since nested groupes are not supported we have to use 
     regular css for the nested dropdowns 
  */
  li>ul                 { transform: translatex(100%) scale(0) }
  li:hover>ul           { transform: translatex(101%) scale(1) }
  li > button svg       { transform: rotate(-90deg) }
  li:hover > button svg { transform: rotate(-270deg) }

  /* Below styles fake what can be achieved with the tailwind config
     you need to add the group-hover variant to scale and define your custom
     min width style.
  	 See https://codesandbox.io/s/tailwindcss-multilevel-dropdown-y91j7?file=/index.html
  	 for implementation with config file
  */
  .group:hover .group-hover\:scale-100 { transform: scale(1) }
  .group:hover .group-hover\:-rotate-180 { transform: rotate(180deg) }
  .scale-0 { transform: scale(0) }
  .min-w-32 { min-width: 8rem }
</style>

</head>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/3.0.1/iconfont/material-icons.min.css" integrity="sha256-x8PYmLKD83R9T/sYmJn1j3is/chhJdySyhet/JuHnfY=" crossorigin="anonymous" />
<link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;700;900&display=swap" rel="stylesheet">
<style>
  html,
body {
  font-family: "Rubik", sans-serif;
}

/* navigation 
 - show navigation always on the large screen devices with (min-width:1024)
*/

@media (min-width: 1024px) {
  .top-navbar {
    display: inline-flex !important;
  }
}

</style>

<nav class="flex items-center bg-white w-full p-3 flex-wrap border-b-2 right-0 absolute">
      <button
        class="text-indigo-600 inline-flex p-3 hover:bg-indigo-600 rounded lg:hidden ml-auto hover:text-white outline-none nav-toggler"
        data-target="#navigation"
      >
        <i class="material-icons">menu</i>
      </button>
      <div
        class="hidden top-navbar w-full lg:inline-flex lg:flex-grow lg:w-auto"
        id="navigation"
      >
        <div
          class="lg:inline-flex lg:flex-row lg:ml-auto lg:w-auto w-full lg:items-center items-start  flex flex-col lg:h-auto hidden lg:block"
        >
          <a
            href="https://www.menuio.co.uk/admin/help"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white"
          >
            <span><i class="fa fa-question-circle" aria-hidden="true"></i></span>
          </a>

          <div class="group inline-block">
  <button
    class="lg:inline-flex px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white min-w-32"
  >
    <span><i class="fa fa-user" aria-hidden="true"></i></span>
  </button>
  <ul
    class="bg-white border rounded-sm transform scale-0 group-hover:scale-100 absolute 
  transition duration-150 ease-in-out origin-top min-w-32"
  >
    <li> <%= link_to "Sign Out", destroy_user_session_path, class:"rounded-sm px-3 py-1 hover:bg-gray-100" %> </li>

         
  </ul>
</div>

        </div>
         <div
          class="lg:inline-flex lg:flex-row lg:ml-auto lg:w-auto w-full lg:items-center items-start  flex flex-col lg:h-auto lg:hidden"
        >
          <a
            href="#"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white "
          >
            <span>Account</span>
          </a>
          <a
            href="#"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white"
          >
            <span>Help</span>
          </a>

           <%= link_to "Dashboard", admin_index_path, class:"lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white" %>

          <%= link_to "Orders", admin_order_path, class:"lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white" %>

          <%= link_to "Orders Archive", admin_orderarchive_path, class:"lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white" %>

          <%= link_to "Inventory Management", admin_products_path, class:"lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white" %>
        </div>
      </div>
    </nav>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
<script>
  $(document).ready(function() {
  $(".nav-toggler").each(function(_, navToggler) {
    var target = $(navToggler).data("target");
    $(navToggler).on("click", function() {
      $(target).animate({
        height: "toggle"
      });
    });
  });
});
</script>

<body>
  <div x-data="{sidebar : true}" class="flex ">

    <!-- Left Sidebar -->
    <div class="h-screen border-r lg:fixed lg:w-56 bg-white left-0 top-0 hidden lg:block" :class="{ 'md:block hidden' : sidebar == false }">
      <div
        class="items-center px-4 py-4 font-bold leading-10 tracking-wider text-center text-indigo-600 uppercase lg:flex h-18 text-md">
        <span class="hidden ml-2 lg:inline-block"><%= current_user.s_name %> Admin</span>
      </div>
      <hr class="mx-4 divider">
      <div class="mx-2 lg:mx-4">
        <hr class="divider">
         <div class="items-center block py-4 tracking-wide text-center text-indigo-600 lg:flex lg:text-sm hover:text-indigo-600">
          <i class="block fa fa-tachometer-alt p-2"></i>
          <%= link_to "Dashboard", admin_index_path, class:"items-center block py-4 tracking-wide text-center text-indigo-600 lg:flex lg:text-sm hover:text-indigo-600" %>
        </div>

        <hr class="divider">
         <div class="items-center block py-4 tracking-wide text-center text-gray-400 lg:flex lg:text-sm hover:text-indigo-600 ">
          <i class="fa fa-list-ul p-2"></i>
          <%= link_to "Orders", admin_order_path, class:"items-center block py-1 tracking-wide text-center text-gray-400 lg:flex lg:text-sm hover:text-indigo-600" %>
        </div>

        <hr class="divider">
         <div class="items-center block py-4 tracking-wide text-center text-gray-400 lg:flex lg:text-sm hover:text-indigo-600">
          <i class="fa fa-archive p-2"></i>
          <%= link_to "Orders Archive", admin_orderarchive_path, class:"items-center block py-1 tracking-wide text-center text-gray-400 lg:flex lg:text-sm hover:text-indigo-600" %>
        </div>

         <div class="items-center block py-4 tracking-wide text-center text-gray-400 lg:flex lg:text-sm hover:text-indigo-600">
          <i class="fa fa-folder p-2"></i>
          <%= link_to "Inventory Management", admin_products_path, class:"items-center block py-4 tracking-wide text-center text-gray-400 lg:flex lg:text-sm hover:text-indigo-600" %>
        </div>

      </div>
    </div>

    <!-- Main content area -->
    <div class="flex-1 bg-gray-100 lg:ml-24 lg:ml-56">

      <!-- Topbar -->

      <!-- Page Heading -->
      <div class="h-24">
      </div>
      <div class="flex-1 px-6 mb-4">
        <h1 class="mb-2 text-3xl text-gray-700"> Admin | Dashboard </h1>

        <!-- Content Row -->
        <div class="grid grid-cols-1 mb-2 -mx-3 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-4">
          <div class="w-full p-3">
            <div class="p-3 bg-white border-l-4 border-indigo-600 rounded-md shadow">
              <div class="flex items-center justify-between p-2">
                <div class="w-full pr-2">
                  <div class="mb-1 text-xs font-semibold leading-5 text-indigo-600 uppercase">Incomplete Orders </div>
                  <div class="text-xl font-bold text-gray-700"> <%= @total_orders %> </div>
                </div>
                <div>
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    viewBox="0 0 24 24" class="w-8 h-8 text-gray-400">
                    <path
                      d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z">
                    </path>
                  </svg>
                </div>
              </div>
            </div>
          </div>

          <div class="w-full p-3">
            <div class="p-3 bg-white border-l-4 border-indigo-600 rounded-md shadow">
              <div class="flex items-center justify-between p-2">
                <div class="w-full pr-2">
                  <div class="mb-1 text-xs font-semibold leading-5 text-indigo-600 uppercase">Total Orders Today</div>
                  <div class="text-xl font-bold text-gray-700"> <%= @total_orders %>  </div>
                </div>
                <div>

                </div>
              </div>
            </div>
          </div>
      
        </div> 


        <div class="flex flex-wrap mb-2 -mx-3">
        <% if current_user.can_receive_payments? %>
        <% else %>

          <div class="w-full p-3 md:w-1/2">
            <div class="bg-white rounded-md shadow">
              <div class="px-5 py-4 font-bold bg-red-200 border-b text-theme-color text-md rounded-t-md">
                Authorize your bank account <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
              </div>
              
              <div class="p-5 leading-7 text-gray-800 text-md">
                <p class="mb-6 text-gray-900"> Before you can start, we need verify to connect to Stripe </p>
                      <%= stripe_connect_button %>
              </div>
            </div>
          </div>
        <% end %>
        </div>
      </div> 


    </div>
  </div>
</body>
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
<script src="public/js/theme.js"></script> 
</html>

app/views/admin/products.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tailwind Admin Template</title>
  <link rel="stylesheet" href="public/css/tailwind.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"
    integrity="sha256-XF29CBwU1MWLaGEnsELogU6Y6rcc5nCkhhx89nFMIDQ=" crossorigin="anonymous"></script>
  <style>
    .divider {
      border-top: 1px solid rgba(255, 255, 255, .15);
    }

    .rotate-15 {
      transform: rotate(-15deg);
    }

    .notification {
      top: 1px;
      right: 1px;
      font-size: 10px;
      padding: 2px 4px;
    }
  </style>
</head>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/3.0.1/iconfont/material-icons.min.css" integrity="sha256-x8PYmLKD83R9T/sYmJn1j3is/chhJdySyhet/JuHnfY=" crossorigin="anonymous" />
<link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;700;900&display=swap" rel="stylesheet">
<style>
  html,
body {
  font-family: "Rubik", sans-serif;
}

/* navigation 
 - show navigation always on the large screen devices with (min-width:1024)
*/

@media (min-width: 1024px) {
  .top-navbar {
    display: inline-flex !important;
  }
}

</style>

<nav class="flex items-center bg-white w-full p-3 flex-wrap border-b-2 right-0 absolute">
      <button
        class="text-indigo-600 inline-flex p-3 hover:bg-indigo-600 rounded lg:hidden ml-auto hover:text-white outline-none nav-toggler"
        data-target="#navigation"
      >
        <i class="material-icons">menu</i>
      </button>
      <div
        class="hidden top-navbar w-full lg:inline-flex lg:flex-grow lg:w-auto"
        id="navigation"
      >
        <div
          class="lg:inline-flex lg:flex-row lg:ml-auto lg:w-auto w-full lg:items-center items-start  flex flex-col lg:h-auto hidden lg:block"
        >
          <a
            href="https://www.menuio.co.uk/admin/help"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white"
          >
            <span><i class="fa fa-question-circle" aria-hidden="true"></i></span>
          </a>
          <a
            href="#"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white"
          >
            <span><i class="fa fa-user" aria-hidden="true"></i></span>
          </a>
        </div>
         <div
          class="lg:inline-flex lg:flex-row lg:ml-auto lg:w-auto w-full lg:items-center items-start  flex flex-col lg:h-auto lg:hidden"
        >
          <a
            href="#"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white "
          >
            <span>Account</span>
          </a>
          <a
            href="#"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white"
          >
            <span>Help</span>
          </a>

          <%= link_to "Dashboard", admin_index_path, class:"lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white" %>

          <%= link_to "Orders", admin_order_path, class:"lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white" %>

          <%= link_to "Orders Archive", admin_orderarchive_path, class:"lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white" %>

          <%= link_to "Inventory Management", admin_products_path, class:"lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white" %>
        </div>
      </div>
    </nav>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
<script>
  $(document).ready(function() {
  $(".nav-toggler").each(function(_, navToggler) {
    var target = $(navToggler).data("target");
    $(navToggler).on("click", function() {
      $(target).animate({
        height: "toggle"
      });
    });
  });
});
</script>

<body>
  <div x-data="{sidebar : true}" class="flex ">

    <!-- Left Sidebar -->
    <div class="h-screen border-r lg:fixed lg:w-56 bg-white left-0 top-0 hidden lg:block" :class="{ 'md:block hidden' : sidebar == false }">
      <div
        class="items-center px-4 py-4 font-bold leading-10 tracking-wider text-center text-indigo-600 uppercase lg:flex h-18 text-md">
        <span class="hidden ml-2 lg:inline-block"><%= current_user.s_name %> Admin</span>
      </div>
      <hr class="mx-4 divider">
      <div class="mx-2 lg:mx-4">
        <hr class="divider">
         <div class="items-center block py-4 tracking-wide text-center text-gray-400 lg:flex lg:text-sm hover:text-indigo-600">
          <i class="block fa fa-tachometer-alt p-2"></i>
          <%= link_to "Dashboard", admin_index_path, class:"items-center block py-4 tracking-wide text-center text-gray-400 lg:flex lg:text-sm hover:text-indigo-600" %>
        </div>

        <hr class="divider">
         <div class="items-center block py-4 tracking-wide text-center text-gray-400 lg:flex lg:text-sm hover:text-indigo-600 ">
          <i class="fa fa-list-ul p-2"></i>
          <%= link_to "Orders", admin_order_path, class:"items-center block py-1 tracking-wide text-center text-gray-400 lg:flex lg:text-sm hover:text-indigo-600" %>
        </div>

        <hr class="divider">
         <div class="items-center block py-4 tracking-wide text-center text-gray-400 lg:flex lg:text-sm hover:text-indigo-600">
          <i class="fa fa-archive p-2"></i>
          <%= link_to "Orders Archive", admin_orderarchive_path, class:"items-center block py-1 tracking-wide text-center text-gray-400 lg:flex lg:text-sm hover:text-indigo-600" %>
        </div>

         <div class="items-center block py-4 tracking-wide text-center text-indigo-600 lg:flex lg:text-sm hover:text-indigo-600">
          <i class="fa fa-folder p-2"></i>
          <%= link_to "Inventory Management", admin_products_path, class:"items-center block py-4 tracking-wide text-center text-indigo-600 lg:flex lg:text-sm hover:text-indigo-600" %>
        </div>
      </div>
    </div>

    <!-- Main content area -->
    <!-- Main content area -->
    <div class="flex-1 bg-gray-100 lg:ml-24 lg:ml-56">

      <!-- Topbar -->

      <!-- Page Heading -->
      <div class="h-24"></div>
      <div class="flex-1 px-6 mb-4">
        <h1 class="mb-2 text-3xl text-gray-700"> Admin | Inventory Management </h1>

           <!-- Charts Row  -->
        <div class="flex flex-wrap mb-2 -mx-3">
          <div class="w-full p-3 ">
            <div class="bg-white rounded-md shadow">
              <div class="px-5 py-4 font-bold bg-white border-b text-theme-color text-center text-md rounded-t-md">
              <div class="flex items-center justify-center">
                Categories 
                <div id='new-category'>
                    <%= link_to "New Category", new_category_path, class: "btn btn-white mb-2 lg:mb-0" %>
                </div>
                </div>
              </div>

                <div class="">
                    <table id="products" class="w-full text-md bg-white shadow-md rounded mb-4">
                      <tbody>
                         <tr class="border-b bg-gray-200">
                                <th class="text-left p-3 px-5">Title</th>
                                <th class="text-left p-3 px-5">Menu</th>
                                <th class="text-left p-3 px-5">Description</th>
                                <!-- <th class="text-left p-3 px-5">Status</th>
                                <th class="text-left p-3 px-5">Toggle Status</th> -->
                                <th class="text-left p-3 px-5">Edit</th>
                            </tr>

                           <%= render @categories %>

                      </tbody>
                    </table>
                </div>
              </div>
            </div>
          </div>
  
        <!-- Charts Row -->
        <div class="flex flex-wrap mb-2 -mx-3">
          <div class="w-full p-3 ">
            <div class="bg-white rounded-md shadow">
              <div class="px-5 py-4 font-bold bg-white border-b text-theme-color text-center text-md rounded-t-md">
                            <div class="flex items-center justify-center">
                Products 
                <div id='new-product'>
                    <%= link_to "New Product", new_product_path, class: "btn btn-white mb-2 lg:mb-0" %>
                </div>
                </div>
              </div>
                <div class="">

                    <table id="products" class="w-full text-md bg-white shadow-md rounded mb-4">
                      <tbody>
                         <tr class="border-b bg-gray-200">
                                <th class="text-left p-3 px-5">Title</th>
                                <th class="text-left p-3 px-5 max-w-sm">Description</th>
                                <th class="text-left p-3 px-5">Price</th>
                                <th class="text-left p-3 px-5">Category</th>
                                <th class="text-left p-3 px-5">Status</th>
                                <th class="text-left p-3 px-5">Toggle Status</th>
                                <th class="text-left p-3 px-5"></th>
                                <th class="text-left p-3 px-5">Action</th>
                            </tr>
                        <%= render @products %>
                      </tbody>
                    </table>
                </div>
              </div>
            </div>
          </div>

        </div>

</html>