config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :communications
  resources :orders do
    member do 
      patch :complete 
    end
  end

  resources :products do
    member do 
      patch :available 
    end
  end
  

  resources :categories do
    member do 
      patch :available 
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  
  resources :categories
  get 'users/show'
  get 'admin/index'
  get 'admin/help'
  get 'admin/order'
  get 'admin/edit'
  get 'admin/products'
  get 'admin/orderarchive'
  get 'admin/landingpage'

  get '/start', to: 'admin#landingpage'
  get '/deals', to: 'admin#deals'
  get '/sales', to: 'communications#new'
  get '/support', to: 'communications#new'
  get '/help', to: 'admin#help'

  get "menu/:id" => "store#menu", as: :menu

  get '' => 'store#profile', constraints: {subdomain: /.+/}

  resources :store
  resources :line_items
  resources :carts
  get 'store/index'
  resources :products
  
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :projects do
    resources :comments, module: :projects
  end
  

  resource :subscription
  root to: 'admin#landingpage'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_product(product)
        current_item = line_items.find_by(product_id: product.id)

        if current_item
          current_item.increment(:quantity)
           else 
          current_item = line_items.build(product_id: product.id)
        end
        current_item
    end 
      
    def total_price
      line_items.to_a.sum{ |item| item.total_price }
    end 
      
end

app/models/category.rb
class Category < ApplicationRecord
    validates :category, presence: true 
    validates :Type, presence: true 

    has_many :products
    belongs_to :user

    enum Type: {
        "Food Menu" => "food",
        "Drinks Menu" => "drink"
    }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/communication.rb
class Communication < ApplicationRecord
    validates :name, :text, :email, :company, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product
  belongs_to :cart, optional: true

  def total_price 
    product.price * quantity
  end 
  
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, dependent: :destroy
    validates :name, presence: true

    enum type: {
      "Table Service" => "1",
      "Collection" => "2"
  }

  
    def add_line_items_from_cart(cart)
      cart.line_items.each do |item|
        item.cart_id = nil
        line_items << item
      end
    end
  
end

app/models/perk.rb
class Perk < ApplicationRecord
  belongs_to :project
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title , :category_id, presence: true 
    validates :price, numericality: { greater_than_or_equal_to: 0.01 }
    belongs_to :user
    belongs_to :category
    has_many :line_items 
    before_destroy :ensure_not_referenced_by_any_line_item
    private 

    def ensure_not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, 'Line Items present')
            throw :abort
        end
    end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_rich_text :description
  has_one_attached :thumbnail
  has_many :comments, as: :commentable
  has_many :perks, dependent: :destroy
  accepts_nested_attributes_for :perks, allow_destroy: true, reject_if: proc { |attr| attr['title'].blank? }

  scope :active, ->{ where(status: "active") }
  scope :inactive, ->{ where(status: "inactive") }

  def backers
    # find users who backed a specific project
  end

  def active?
    status == "active"
  end

  def inactive
    status == "inactive"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:stripe_connect]

  has_many :projects, dependent: :destroy
  has_many :categories

  validates :email, uniqueness:true 
  validates :s_name, presence:true
  validates :username, uniqueness:true 


  def can_receive_payments?
    uid? &&  provider? && access_code? && publishable_key?
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :available]
  before_action :authenticate_user!, except: [:index, :show, :available]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.user = current_user
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
          if current_user.can_receive_payments?
            UploadProductJob.perform_now(@product)
          end
        format.js
        format.html { redirect_to admin_products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_products_path, notice: 'Product was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to admin_products_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def available
    @product.toggle!(:available)
    respond_to do |format|
      format.js
    end
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :category_id, :available)
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def author_of(resource)
    user_signed_in? && resource.user_id == current_user.id
  end

  def cart_count_over_one
    if @cart.line_items.count > 0 
      return "<span class='tag is-dark'>#{@cart.line_items.count}</span>".html_safe
    end
  end  

  def cart_has_items 
    return @cart.line_items.count > 0
  end 

  def admin?
    user_signed_in? && current_user.admin?
  end

  def render_if(condition, record)
    if condition  
      render record
    end
  end

  def stripe_url
    "https://connect.stripe.com/oauth/authorize?response_type=code&client_id=#{Rails.application.credentials.dig(:stripe, :connect_client_id)}&scope=read_write"
  end

  def stripe_connect_button
    link_to stripe_url, class: "btn-stripe-connect" do
      content_tag :span, "Connect with Stripe"
    end
  end


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def purchased_perk(perk)
    user_signed_in? && current_user.perk_subscriptions.include?("#{perk.title.parameterize}-perk_#{perk.id}")
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="w-full max-w-xs">

    <h1 class="mb-6 text-3xl text-center text-black font-bold">Create a Product</h1>
    <br>
  <div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
      <%= form.label :title, class: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
    </div>
    <div class="md:w-2/3">
      <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>
  </div>

  <div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
      <%= form.label :description, class: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
    </div>
    <div class="md:w-2/3">
      <%= form.text_area :description, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>
  </div>

  <div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
      <%= form.label :price, class: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
    </div>
    <div class="md:w-2/3">
      <%= form.text_field :price, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>
  </div>

   <div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
      <h1 class= "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4"> Category </h1>
    </div>
    <div class="md:w-2/3">
      <%= form.select :category_id, current_user.categories.all.map {|c| [c.category, c.id]} %>
    </div>
  </div>

    <div class="actions">
      <%= form.submit "Create", class: "btn btn-default w-full" %>  
    </div>
  </div>
  
<% end %>

app/views/products/_product.html.erb
  <% if request.fullpath.include?('admin') %>

  <style>
  .max {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 200px;
}
  </style>
                            <tr class="border-b hover:bg-orange-100 bg-gray-100">
                                <td class="p-3 px-5"><%= product.title %></td>
                                <td class="p-3 px-5 max"><%= sanitize(product.description) %></td>
                                <td class="p-3 px-5"> <%= sprintf("£%0.02f", product.price ) %></td>
                                
                                <td class="p-3 px-5"><%= product.category.category %></td>
                                <% if (product.available) %>
                                <td class="p-3 px-5"> <span class="rounded bg-green-400 py-1 px-3 text-xs font-bold">active</span> </td>
                                <% else %>
                                 <td class="p-3 px-5"> <span class="rounded bg-yellow-400 py-1 px-3 text-xs font-bold">inactive</span> </td>
                                <% end %>
                                <td><%= link_to 'Mark Available', available_product_path(product.id), method: :patch, data: { confirm: 'Are you sure? | Item will update when you refresh the page.', remote: true}, class: "available rounded py-1 px-3 text-xs font-bold"%></td>
                                <td class="p-3 px-5"><td><%= link_to 'Edit', edit_product_path(product) %> | <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?', remote: true}, class: "delete rounded bg-red-400 py-1 px-3 text-xs font-bold" %></td>
                            </tr>
<% else %>
  <% if (product.available) %>
<div class="tab-content overflow-hidden border-l-2 bg-gray-100 border-indigo-500 leading-normal">
                 <ul class="flex flex-col p-2 ">
                    <li class="border-gray-400 flex flex-row mb-2">
                      <div class="lg:w-1/4 lg:mr-8 w-full select-none cursor-pointer bg-white rounded-lg flex flex-1 items-center p-4  transition duration-500 shadow ease-in-out transform hover:-translate-y-1 hover:shadow-lg">
                            <div class="flex-1 pl-1 mr-0">
                               <div class="font-semibold"><%= product.title %></div>
                              <div class="text-gray-600 font-normal text-xs"> <%= product.description%> </div>
                          <div class="text-black font-medium text-sm mt-4 py-2 bg-blue rounded-full"> <%= sprintf("£%0.02f", product.price ) %> </div>
                        <div id="<%= product.id %>"></div>
                            </div>
                            <div class="flex-2 pl-1 mr-0">
                          <%= button_to 'Add to Order', line_items_path(product_id: product), class:"text-black font-medium text-sm mt-8 px-4 py-2 bg-blue rounded-full" %>
                        <div id="<%= product.id %>"></div>
                            </div>
                      </div>
            </li>
        </ul>
      </div>
  <% else %>

  <% end %>

<% end %>

app/views/products/available.js.erb
$('table#products tbody').removeAttr("<%= j render @product %>");

app/views/products/create.js.erb
$('#new-product form').remove();
$('#new-product a').show();
$('table#products tbody').append("<%= j render @product %>")

app/views/products/destroy.js.erb
$('.delete').bind('ajax:success', function() {
     $(this).closest('tr').fadeOut();
});

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', admin_products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?', remote: true}, class: "delete" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<div class="max-w-lg m-auto">
 <% if current_user.can_receive_payments? %>
    <%= render 'form', product: @product %>
    <%= link_to "Back", admin_products_path %>
  <% else %>
    <%= render 'form', product: @product %>
    <%= link_to "Back", admin_products_path %>
  <% end %>
</div>

app/views/products/new.js.erb
$('#new-product a').hide().parent().append("<%= j render 'form', product: @product %>")

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Status:</strong>
  <span> <%= @product.available  %> </span>
</p>


<%= link_to 'Mark Unavailable', available_product_path(@product), method: :patch, remote: true %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>